# Generated by Django 4.2.16 on 2024-11-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('author', models.CharField(help_text='Author of the book', max_length=255)),
                ('genre', models.CharField(help_text='Genre of the book', max_length=100)),
                ('publication_date', models.DateField(help_text='Publication date of the book')),
                ('isbn', models.CharField(help_text='13-character ISBN number', max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'inventory',
                'ordering': ['-publication_date'],
            },
        ),
    ]
